---
title: "R Notebook"
output: html_notebook
---
```{r}
library(keras)
library(dplyr)
```

```{r loading_data}
stock_df <- read.csv("Final_data_with_reddit.csv")
stock_df <- stock_df[,3:11]
head(stock_df)
```


```{r}
stock_df <- stock_df%>%mutate(stock_val = (High+Low)/2)
```


```{r}
stock_df <- stock_df%>%select(Date,company_name,company_name_full,stock_val,Volume,sentiment_score,sentiment_common,target)
stock_df
```

```{r}
stock_df$Date <- as.Date(stock_df$Date)
```

```{r}
sample_size = floor(0.8*nrow(stock_df))
set.seed(777)
train_stock_df = stock_df%>%filter(Date<'2014-01-01')
test_stock_df = stock_df%>%filter(Date>='2014-01-01')
```

```{r}
train_stock <- train_stock_df%>%select(stock_val,Volume,sentiment_score,sentiment_common)
test_stock <- test_stock_df%>%select(stock_val,Volume,sentiment_score,sentiment_common)
train_target <- train_stock_df%>%select(target)
test_target <- test_stock_df%>%select(target)
```

```{r}
train_data <- scale(train_stock) 
col_means_train <- attr(train_data, "scaled:center") 
col_stddevs_train <- attr(train_data, "scaled:scale")
test_data <- scale(test_stock, center = col_means_train, scale = col_stddevs_train)
```

```{r}
train_data <- as.data.frame(train_stock)
test_data <- as.data.frame(train_stock)
```

```{r}

plotting_df <- stock_df%>%select(Date,stock_val,Volume,sentiment_score,sentiment_common,target)
```

```{r}
plotting_df%>%ggplot() + 
  geom_point(aes(x = stock_val, y = target), color = "red",alpha = 0.5)
```


```{r}
plotting_df%>%ggplot() + 
  geom_point(aes(x = log(1/sentiment_common), y = target), color = "red",alpha = 0.5)
```




```{r}
plotting_df%>%ggplot() + 
  geom_point(aes(x = log(1/Volume), y = target), color = "red",alpha = 0.5)

```



```{r}
plot(density(plotting_df$target), main="Density Plot: Stock Prices", ylab="Frequency", sub=paste("Skewness:", round(e1071::skewness(plotting_df$target), 2)))

```



```{r}
sample_size = floor(0.8*nrow(stock_df))
set.seed(777)
train_stock_df = plotting_df%>%filter(Date<'2014-01-01')
test_stock_df = plotting_df%>%filter(Date>='2014-01-01')
```







```{r}
linear_model <- lm(target ~ stock_val+log(1/Volume)+sentiment_score+sentiment_common, data=train_stock_df)  # build linear regression model on full data
print(linear_model)
```




```{r}
summary(linear_model)

```


From the linear modelling we see that the most important factors are stock_val, Volume, and the sentiment_score of the company news. The common news data is nto considered to be incredibly informative to the Data. 

```{r}
predicted <- predict(linear_model,test_stock_df)
actuals_preds <- data.frame(cbind(actuals=test_stock_df$target, predicteds=predicted))
actuals_preds
```

```{r}
correlation_accuracy <- cor(actuals_preds) 

```


```{r}
library(class)
library(LiblineaR)
library(e1071)
SVR_model <- svm(target ~ stock_val+log(1/Volume)+sentiment_score+sentiment_common, data=train_stock_df)  # build linear regression model on full data
print(SVR_model)
```

```{r}
pred_svr <- predict(SVR_model,test_stock_df)
actuals_preds_svr <- data.frame(cbind(actuals=test_stock_df$target, predicteds=pred_svr))
actuals_preds_svr
```
```{r}
correlation_accuracy_svr <- cor(actuals_preds_svr) 

```