---
title: "R Notebook"
output: html_notebook
---

```{r}
library(dplyr)
```

```{r}
library('googledrive')
api = "Nql4mIbzy44BETXG70DGesoOoXlnXeKH"
```



```{r}
if (!require("jsonlite")) install.packages("jsonlite")
library(jsonlite)
#################################################################################
####            function - search news article with API                      ####
nytime = function (keyword,year) {
  searchQ = URLencode(keyword)
  url = paste('http://api.nytimes.com/svc/search/v2/articlesearch.json?q=',searchQ,
              '&begin_date=',year,'0101&end_date=',year,'1231&api-key=',api,sep="")
  #get the total number of search results
  initialsearch = fromJSON(url,flatten = T)
  maxPages = round((initialsearch$response$meta$hits / 10)-1)
  
  #try with the max page limit at 10
  maxPages = ifelse(maxPages >= 50, 50, maxPages)
  
  #creat a empty data frame
  df = data.frame(id=as.numeric(),created_time=character(),snippet=character(),
                  headline=character(),news_desk = character())
  
  #save search results into data frame
  for(i in 0:maxPages){
    #get the search results of each page
    nytSearch = fromJSON(paste0(url, "&page=", i), flatten = T) 
    temp = data.frame(id=1:nrow(nytSearch$response$docs),
                      created_time = nytSearch$response$docs$pub_date,
                      snippet = nytSearch$response$docs$snippet,
                      headline = nytSearch$response$docs$headline.main,
                      news_desk = nytSearch$response$docs$news_desk)
    df=rbind(df,temp)
    Sys.sleep(5) #sleep for 5 second
  }
  return(df)
}
```

```{r}
year_start = 2009
year_end = 2015
for(company in company_list){
  df = nytime(company,year_start,year_end)
}

```

```{r}
dt = nytime('Microsoft Corporation',2018)
```

```{r}
dt1 = nytime('Microsoft',2018)
```

```{r}
df1<- dt1
df1$created_time <- as.Date(df1$created_time, "%Y-%m-%d")
df1<-df1[order(df1$created_time),]
df1
```

```{r}
df1[!duplicated(df1$headline),]
```

```{r}
df$created_time <- as.Date(df$created_time, "%Y-%m-%d")
df<-df[order(df$created_time),]
df
```

```{r}
df1<- dt
df<-dt[order(dt$created_time),]
df
```

```{r}
df$created_time <- as.Date(df$created_time, "%Y-%m-%d")
df<-df[order(df$created_time),]
df
```

```{r}
drive_upload('microsoft.csv',path = 'Stock_Data_R', type='spreadsheet')
```