---
title: "Sentiment Analyser"
output: html_notebook
---

```{r}
library(sentimentr)
library(dplyr)
```

```{r}
mytext <- c(
  'do you like it?  But I hate really bad dogs',
  'I am the best friend.',
  "Do you really like it?  I'm not a fan",
  "It's like a tree.",
  "Microsoft is an amazing girl. It is doing really well and has made us all proud.",
  "Facebook is such a scam. It should be wiped out from the face of this earth.",
  "The Federal Reserve granted the company’s request to change its status, giving it access to low-cost financing."
)

typeof(mytext)
## works on a character vector but not the preferred method avoiding the 
## repeated cost of doing sentence boundary disambiguation every time 
## `sentiment` is run.  For small batches the loss is minimal.
## Not run: 
sentiment_by(mytext)
```

```{r load data}
news_data <- read.csv("company_data.csv")
head(news_data)
```

```{r get_sentiment}
news_data = mutate(news_data, news_data_new = sentiment_by(as.character(headline))$ave_sentiment)
```

```{r}
news_data
```

```{r}
d <- density(news_data$news_data_new)
plot(d, main="Dist")
polygon(d, col="red", border="blue")
```

```{r}
stock_numbers <- read.csv("combined_dataframe_djia.csv")
head(stock_numbers)
```

```{r}
stock_numbers_ave <- stock_numbers%>%mutate(average_price = (High+Low)/2)%>%select(Date,company_name,High,Low,Volume,average_price)
stock_numbers_ave
```
```{r}
# library(Hmisc)
# stock_numbers_ave$lagged <- Lag(stock_numbers_ave$average_price, +1)
# stock_numbers_ave

stock_numbers_ave <- stock_numbers_ave %>%group_by(company_name) %>%mutate(target = dplyr::lead(average_price, n = 1, default = NA))%>%ungroup()
```



```{r}
news_data
```

```{r}
levels(news_data$company_name)
```

```{r}
levels(stock_numbers_ave$company_name)
```

```{r}
company_ticker_dict = list("AAPL"="Apple",
                           "AXP"="American Express",
                           "BA"="Boeing",
                           "CAT"="Caterpillar Inc.",
                           "CSCO"="Cisco",
                           "CVX"="Chevron Corporation",
                           "DD"="Dow",
                           "DIS"="The Walt Disney Company",
                           "GS"="Goldman Sachs",
                           "HD"="The Home Depot",
                           "IBM"="IBM",
                           "INTC"="Intel",
                           "JNJ"="Johnson & Johnson",
                           "JPM"="JPMorgan Chase",
                           "KO"="Coca-Cola",
                           "MCD"="McDonald's",
                           "MMM"="3M",
                           "MRK"="Merck & co",
                           "MSFT"="Microsoft",
                           "NKE"="Nike",
                           "PFE"="Pfizer",
                           "PG"="Procter & Gamble",
                           "TRV"=" The Travelers Companies",
                           "UNH"="United Health Group",
                           "UTX"="United Technologies",
                           "V"="Visa Inc.",
                           "VZ"="Verizon",
                           "WBA"="Walgreens Boots Alliance",
                           "WMT"="Walmart",
                           "XOM"="ExxonMobil" )

#stock_numbers_ave%>%mutate(company_full_name = company_ticker_dict[paste0("'",company_name,"'")])

company_name_list = list()
for (i in stock_numbers_ave$company_name){
  company_name_list <- append(company_name_list,company_ticker_dict[i])
}


```

```{r}
company_names_list <- stack(company_name_list)$values
```

```{r}
stock_numbers_ave <- stock_numbers_ave%>%mutate(company_name_full = company_names_list)
head(stock_numbers_ave)
```

```{r}
news_data%>%filter(company_name == 'IBM')
```

```{r}
a <- left_join(stock_numbers_ave, news_data, by = c("Date" = "created_time","company_name_full" = "company_name"))
a
```


```{r}
final_df <- na.omit(a)
final_df%>%mutate(sentiment_score=news_data_new)%>%select(Date,company_name,company_name_full,High,Low,Volume,sentiment_score,target)
```



```{r}

```






# ```{r}
# library(jsonlite)
# test <- fromJSON("https://api.iextrading.com/1.0/ref-data/symbols")
# test
# final_stocks <- left_join(stock_numbers_ave,test,by=c("company_name"="symbol"))%>%select(Date,company_name,average_price,name)
# final_stocks$name <- as.factor(final_stocks$name)
# levels(final_stocks$name)
# ```
